### ISSUE TITLE
Autobuyer disp

### ISSUE THREAD

**Issue by Dystopia-user181** [IvarK/AntimatterDimensionsSourceCode#1849]
**Issue**
It is not clear when autobuyers are disabled.

**Solution thing**
Use grayscale for the checkmarks apart from decreasing opacity. Alternatively set them all to yellow and use a "-" symbol.
```css
.o-autobuyer-toggle-checkbox__label--disabled {
    opacity: 0.6;
    filter: grayscale(0.8);
}
```

The button that toggles autobuyers should have class o-primary-btn--disabled instead of o-primary-btn if autobuyers are disabled

Change button text to `Enable autobuyers` -> `Autobuyers disabled` and `Disable autobuyers` -> `Autobuyers enabled`
